server:
  # Hostname argument.
  bindIP: 0.0.0.0
  # Port argument.
  bindPort: 8081
public:
  # The base url to use when connecting to this endpoint. This is required to
  # inform other endpoints when doing direct endpoint to endpoint transfers.
  baseURL: ws://0.0.0.0:8081
encoder:
  # The gstreamer h264 encoder to use. 'x264' and 'nvh264' are supported ('vaapih264' is currently broken). 'x264'
  # is a pure software encoder. While 'nvh264' is a hw accelerated encoder for Nvidia based GPUs.
  # see https://gstreamer.freedesktop.org/documentation/x264/index.html
  # see https://gstreamer.freedesktop.org/documentation/nvenc/nvh264enc.html
  h264Encoder: x264
  # Maximum number of pixels an image can have before we switch to h264 encoding.
  # If lower, png encoding is used.
  # Png encoding has perfect image quality but has a far larger image size than
  # h264. Default is (256*256)-1 = 0xFFFF
  maxPngBufferSize: 0xffff
logging:
  # "fatal" | "error" | "warn" | "info" | "debug" | "trace"
  level: info
