server:
  # Hostname argument.
  bindIP: 0.0.0.0
  # Port argument.
  bindPort: 8081
  # CORS allowed origins, used when doing cross-origin requests. Value can be * or comma seperated domains.
  allowOrigin: '*'
public:
  # The base url to use when connecting to this endpoint. This is used when doing direct proxy to proxy connections.
  baseURL: http://localhost:8081
encoder:
  # Path of the render device that should be used for hardware acceleration. e.g. /dev/dri/renderD128
  renderDevice: /dev/dri/renderD128
  # The gstreamer h264 encoder to use. 'x264' and 'nvh264' are supported ('vaapih264' is currently broken). 'x264'
  # is a pure software encoder. While 'nvh264' is a hw accelerated encoder for Nvidia based GPUs.
  # see https://gstreamer.freedesktop.org/documentation/x264/index.html
  # see https://gstreamer.freedesktop.org/documentation/nvenc/nvh264enc.html
  h264Encoder: x264
logging:
  # "fatal" | "error" | "warn" | "info" | "debug" | "trace"
  level: info
