openapi: 3.0.3
info:
  title: WebFS
  description: WebFS Rest API specification.
  version: 1.0.0

servers:
  - url: /webfs/v1

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
  schemas:
    webfd:
      type: object
      properties:
        fd:
          description: The native FD
          type: integer
          format: int32
          minimum: 0
        type:
          description: The file type of the native FD
          type: string
          enum:
            - pipe-read
            - pipe-write
            - shm
            - unknown
        location:
          description: The url where the native FD originated from and where it can be accessed eg. for reading.
          type: string
          format: uri

paths:
  /mkfifo:
    post:
      tags:
        - webfs
      summary: Creates a new pipe and returns a read+write webfd pair.
      operationId: mkfifo
      responses:
        201:
          description: Pipe pair was succesfully created.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/webfd'
                  minItems: 2
                  maxItems: 2
                example:
                  - fd: 8
                    type: pipe-read
                    location: https://some.proxy.com:8181
                  - fd: 9
                    type: pipe-write
                    location: https://some.proxy.com:8181
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /mkstemp-mmap:
    post:
      tags:
        - webfs
      summary: Creates a tempororay file and returns a memory mapped webfd of the uploaded data.
      operationId: mkstempMmap
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        201:
          description: Data was succesfully uploaded and mapped to a shared memory file.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/webfd'
              example:
                fd: 10
                type: shm
                location: https://some.proxy.com:8181
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /webfd/{fd}/read:
    get:
      tags:
        - webfd
      summary: Read a chunk from a webfd.
      operationId: read
      parameters:
        - in: path
          name: fd
          description: the native fd
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: count
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
          description: Read up to count bytes from file descriptor fd.
      responses:
        200:
          description: Content sent succesfully.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        401:
          $ref: '#/components/responses/UnauthorizedError'
        400:
          description: Bad request. FD and count must be an integer greater than or equal to zero.
        404:
          description: FD not known.
        5XX:
          description: Unexpected error.
  /webfd/{fd}/readstream:
    get:
      tags:
        - webfd
      summary: Read and stream all data from a webfd until EOF.
      operationId: stream
      parameters:
        - in: path
          name: fd
          description: the native fd
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: chunkSize
          required: false
          schema:
            type: integer
          description: Stream data in chunks with a maximum size. Defaults to 64 kilo bytes.
      responses:
        200:
          description: All content sent succesfully.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        401:
          $ref: '#/components/responses/UnauthorizedError'
        400:
          description: Bad request. FD and chunkSize must be an integer greater than or equal to zero.
        404:
          description: FD not known.
        5XX:
          description: Unexpected error.
