description: The main config file
type: object
additionalProperties: false
properties:
  server:
    description: General server settings
    type: object
    additionalProperties: false
    properties:
      bindIP:
        type: string
        description: The ip address to bind to
      bindPort:
        type: integer
        minimum: 1
        maximum: 65535
        description: The port to bind to
    required:
      - bindIP
      - bindPort
  public:
    description: Settings for the public endpoint
    type: object
    additionalProperties: false
    properties:
      baseURL:
        type: string
        format: uri
        description: The base url to use when connecting to this endpoint. This is required to  inform other endpoints when doing direct endpoint to endpoint transfers.
    required:
      - baseURL
  encoder:
    description: Encoder settings
    type: object
    additionalProperties: false
    properties:
      h264Encoder:
        description: |
           The gstreamer h264 encoder to use. For now only 'x264' or 'nvh264' is supported. 'x264'
           is a pure software encoder. While 'nvh264' is a hw accelerated encoder for Nvidia based GPUs.
           see https://gstreamer.freedesktop.org/documentation/x264/index.html
           see https://gstreamer.freedesktop.org/documentation/nvenc/nvh264enc.html
        type: string
        enum:
          - x264
          - nvh264
          - vaapih264
      maxPngBufferSize:
        description: |
          Maximum number of pixels an image can have before we switch to h264 encoding.
          If lower, png encoding is used.
          Png encoding has perfect image quality but has a far larger image size than
          h264. Default is (256*256)-1 = 0xFFFF
        type: integer
        minimum: 1
    required:
      - h264Encoder
      - maxPngBufferSize
  logging:
    description: Logging options
    type: object
    additionalProperties: false
    properties:
      level:
        type: string
        description: Log Level
        enum:
          - fatal
          - error
          - warn
          - info
          - debug
          - trace
    required:
      - level
required:
  - server
  - public
  - encoder
  - logging

