description: The main config file
type: object
additionalProperties: false
properties:
  server:
    description: General server settings
    type: object
    additionalProperties: false
    properties:
      http:
        description: Config related to communication over http and websocket
        type: object
        additionalProperties: false
        properties:
          bindIP:
            type: string
            description: The ip address to bind to for websocket and http connections
          bindPort:
            type: integer
            minimum: 1
            maximum: 65535
            description: The port to bind to for websocket and http connections
          allowOrigin:
            type: string
            description: The allowed origins during CORS checks.
        required:
          - bindIP
          - bindPort
          - allowOrigin
    required:
      - http
  public:
    description: Settings for the public endpoint
    type: object
    additionalProperties: false
    properties:
      baseURL:
        type: string
        format: uri
        description: The base ws(s) url to use when connecting to this endpoint. This is also required to inform other endpoints when doing direct endpoint to endpoint transfers.
      applications:
        type: object
        additionalProperties:
          type: object
          properties:
            executable:
              type: string
              format: uri-reference
            path:
              type: string
              format: uri-reference
          required:
            - executable
            - path
    required:
      - baseURL
      - applications
  encoder:
    description: Encoder settings
    type: object
    additionalProperties: false
    properties:
      renderDevice:
        description: |
          Path of the render device that should be used for hardware acceleration. e.g. /dev/dri/renderD128
        type: string
      h264Encoder:
        description: |
           The gstreamer h264 encoder to use. For now only 'x264' or 'nvh264' is supported. 'x264'
           is a pure software encoder. While 'nvh264' is a hw accelerated encoder for Nvidia based GPUs.
           see https://gstreamer.freedesktop.org/documentation/x264/index.html
           see https://gstreamer.freedesktop.org/documentation/nvenc/nvh264enc.html
        type: string
        enum:
          - x264
          - nvh264
          - vaapih264
    required:
      - renderDevice
      - h264Encoder
required:
  - server
  - public
  - encoder
  - logging

