description: The main config file
type: object
additionalProperties: false
properties:
  server:
    description: General server settings
    type: object
    additionalProperties: false
    properties:
      http:
        description: Config related to communication over http and websocket
        type: object
        additionalProperties: false
        properties:
          bindIP:
            type: string
            description: The ip address to bind to for websocket and http connections
          bindPort:
            type: integer
            minimum: 1
            maximum: 65535
            description: The port to bind to for websocket and http connections
          allowOrigin:
            type: string
            description: The allowed origins during CORS checks.
        required:
          - bindIP
          - bindPort
          - allowOrigin
      webrtc:
        description: Config related to communication over webrtc data-channels
        type: object
        additionalProperties: false
        properties:
          iceServers:
            description: The ice servers to use with the rtc peer connection
            type: array
            items:
              type: object
              properties:
                urls:
                  type: array
                  items:
                    type: string
                username:
                  type: string
                credential:
                  type: string
              required:
                - urls
          portRangeMin:
            type: integer
            minimum: 0
            maximum: 65535
            description: The minimum port for UDP RTC datachannel connections, default 0
          portRangeMax:
            type: integer
            minimum: 0
            maximum: 65535
            description: The maximum port for UDP RTC datachannel connections, default 65535
    required:
      - http
      - webrtc
  public:
    description: Settings for the public endpoint
    type: object
    additionalProperties: false
    properties:
      baseURL:
        type: string
        format: uri
        description: The base url to use when connecting to this endpoint. This is required to  inform other endpoints when doing direct endpoint to endpoint transfers.
    required:
      - baseURL
  encoder:
    description: Encoder settings
    type: object
    additionalProperties: false
    properties:
      renderDevice:
        description: |
          Path of the render device that should be used for hardware acceleration. e.g. /dev/dri/renderD128
        type: string
      h264Encoder:
        description: |
           The gstreamer h264 encoder to use. For now only 'x264' or 'nvh264' is supported. 'x264'
           is a pure software encoder. While 'nvh264' is a hw accelerated encoder for Nvidia based GPUs.
           see https://gstreamer.freedesktop.org/documentation/x264/index.html
           see https://gstreamer.freedesktop.org/documentation/nvenc/nvh264enc.html
        type: string
        enum:
          - x264
          - nvh264
          - vaapih264
    required:
      - renderDevice
      - h264Encoder
  logging:
    description: Logging options
    type: object
    additionalProperties: false
    properties:
      level:
        type: string
        description: Log Level
        enum:
          - fatal
          - error
          - warn
          - info
          - debug
          - trace
    required:
      - level
required:
  - server
  - public
  - encoder
  - logging

