version: '3.4'
services:
  compositor-proxy:
    runtime: nvidia
    build:
      context: .
      dockerfile: ./Dockerfile
    privileged: false
    user: "1000:1000"
    ipc: host
    volumes:
      - xdg-runtime-dir:/xdg-runtime-dir
      - x11-unix:/tmp/.X11-unix
      - ${PWD}/src/config.yaml:/app/dist/config.yaml
      - /dev/dri/renderD129:/dev/dri/renderD129:rw
      - /dev/dri/card1:/dev/dri/card1:rw
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD129
      - /dev/dri/card1:/dev/dri/card1
    ports:
      - 8081:8081
    environment:
      COMPOSITOR_SESSION_ID: test123
      XDG_RUNTIME_DIR: /xdg-runtime-dir
      XAUTHORITY: /tmp/.X11-unix/Xauthority
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
  gtk3-demo:
    runtime: nvidia
    pid: 'service:compositor-proxy'
    build:
      context: example-apps/gtk3-demo
      dockerfile: Dockerfile
    privileged: false
    user: "1000:1000"
    volumes:
      - xdg-runtime-dir:/xdg-runtime-dir
      - /dev/dri/renderD129:/dev/dri/renderD129:rw
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD129
    environment:
      XDG_RUNTIME_DIR: /xdg-runtime-dir
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    restart: always
  gtk4-demo:
    runtime: nvidia
    pid: 'service:compositor-proxy'
    build:
      context: example-apps/gtk4-demo
      dockerfile: Dockerfile
    privileged: false
    user: "1000:1000"
    volumes:
      - xdg-runtime-dir:/xdg-runtime-dir
      - /dev/dri/renderD129:/dev/dri/renderD129:rw
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD129
    environment:
      XDG_RUNTIME_DIR: /xdg-runtime-dir
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    restart: always
  alacritty:
    runtime: nvidia
    pid: 'service:compositor-proxy'
    build:
      context: example-apps/alacritty
      dockerfile: Dockerfile
    privileged: false
    user: "1000:1000"
    volumes:
      - xdg-runtime-dir:/xdg-runtime-dir
      - /dev/dri/renderD129:/dev/dri/renderD129:rw
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD129
    environment:
      WAYLAND_DISPLAY: wayland-0
      XDG_RUNTIME_DIR: /xdg-runtime-dir
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    restart: always
  xterm:
    runtime: nvidia
    pid: 'service:compositor-proxy'
    build:
      context: example-apps/xterm
      dockerfile: Dockerfile
    privileged: false
    user: "1000:1000"
    volumes:
      - xdg-runtime-dir:/xdg-runtime-dir
      - x11-unix:/tmp/.X11-unix
      - /dev/dri/renderD129:/dev/dri/renderD129:rw
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD129
    environment:
      XAUTHORITY: /tmp/.X11-unix/Xauthority
      XDG_RUNTIME_DIR: /xdg-runtime-dir
      DISPLAY: ':1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    restart: always
  glxgears:
    runtime: nvidia
    pid: 'service:compositor-proxy'
    build:
      context: example-apps/glxgears
      dockerfile: Dockerfile
    ipc: host
    privileged: false
    user: "1000:1000"
    volumes:
      - xdg-runtime-dir:/xdg-runtime-dir
      - x11-unix:/tmp/.X11-unix
      - /dev/dri/renderD129:/dev/dri/renderD129:rw
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD129
    environment:
      XAUTHORITY: /tmp/.X11-unix/Xauthority
      XDG_RUNTIME_DIR: /xdg-runtime-dir
      DISPLAY: ':1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    restart: always
volumes:
  xdg-runtime-dir:
    driver_opts:
      type: tmpfs
      device: tmpfs
  x11-unix:
    driver_opts:
      type: tmpfs
      device: tmpfs
