export enum CursorType {
  XWM_CURSOR_TOP,
  XWM_CURSOR_BOTTOM,
  XWM_CURSOR_LEFT,
  XWM_CURSOR_RIGHT,
  XWM_CURSOR_TOP_LEFT,
  XWM_CURSOR_TOP_RIGHT,
  XWM_CURSOR_BOTTOM_LEFT,
  XWM_CURSOR_BOTTOM_RIGHT,
  XWM_CURSOR_LEFT_PTR,
}
