openapi: 3.0.3
info:
  title: Compositor Proxy REST API
  description: A set of REST API endpoints exposed by the Compositor Proxy.
  version: 1.0.0

servers:
  - url: http://localhost:8080

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Greenfield-Proxy-Session-Key
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      content:
        text/plain:
          schema:
            type: string
  schemas:
    ProxyFD:
      description: >
        This type carefully mimics a native file descriptor and adds additional information to make it usable in a 
        remote context.
      type: object
      required:
        - handle
        - type
        - host
        - proxySessionKey
      properties:
        handle:
          description: The native FD
          example: 12
          type: integer
          format: int32
          minimum: 0
          readOnly: true
        type:
          description: >
            The file type of the native FD. 'unknown' type means that FD was created by an external application, in which
            case the 'type' should be manually updated to a more concrete type before doing any operations on the ProxyFD.
          type: string
          enum:
            - pipe-read
            - pipe-write
            - shm
            - unknown
          readOnly: false
        host:
          description: The url where this ProxyFD originated from and where it can be accessed e.g. for reading or writing.
          example: 'https://proxy-endpoint.com:8081'
          type: string
          format: uri
          pattern: '^(https?)://'
          readOnly: true
        proxySessionKey:
          description: key of the proxy session this ProxyFD originated from
          type: string
          readOnly: true

paths:
  /session:
    post:
      tags:
        - proxy
      summary: Create a new proxy session
      operationId: session
      responses:
        201:
          description: Session was successfully created.
          content:
            application/json:
              schema:
                type: object
                required:
                  - sessionKey
                properties:
                  sessionKey:
                    description: The proxy session id
                    type: string
                    readOnly: true

  /client/{clientId}/surface/{surfaceId}/encoder/keyframe:
    post:
      tags:
        - encoder
      summary: Encode a new keyframe.
      operationId: keyframe
      parameters:
        - in: path
          name: clientId
          description: the client id
          required: true
          schema:
            type: string
        - in: path
          name: surfaceId
          description: the surface id
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: Describes when the key frame should be generated.
              type: object
              required:
                - bufferId
                - bufferCreationSerial
                - bufferContentSerial
              properties:
                bufferId:
                  type: number
                  format: int32
                  minimum: 1
                  description: The buffer id.
                bufferContentSerial:
                  type: number
                  format: int32
                  minimum: 1
                  description: The buffer content serial.
                bufferCreationSerial:
                  type: number
                  format: int32
                  minimum: 1
                  description: The buffer creation serial.
      responses:
        202:
          description: Key frame successfully requested.
        401:
          $ref: '#/components/responses/UnauthorizedError'
        400:
          description: Bad request. Bad or no content.
          content:
            text/plain:
              schema:
                type: string
        404:
          description: client, surface or buffer not found.
          content:
            text/plain:
              schema:
                type: string
  /mkfifo:
    post:
      tags:
        - io
      summary: Creates a new pipe and returns a read+write ProxyFD pair.
      operationId: mkfifo
      responses:
        201:
          description: Pipe pair was successfully created.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProxyFD'
                example:
                  - fd: 8
                    type: pipe-read
                    location: https://some.proxy.com:8181
                  - fd: 9
                    type: pipe-write
                    location: https://some.proxy.com:8181
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /mkstemp-mmap:
    post:
      tags:
        - io
      summary: Creates a temporary file and returns a memory mapped ProxyFD of the uploaded data.
      operationId: mkstempMmap
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        201:
          description: Data was successfully uploaded and mapped to a shared memory file.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProxyFD'
              example:
                fd: 10
                type: shm
                location: https://some.proxy.com:8181
        400:
          description: Bad request. Bad or no content.
          content:
            text/plain:
              schema:
                type: string
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /fd/{fd}:
    delete:
      tags:
        - io
      summary: close the native fd.
      operationId: close
      parameters:
        - in: path
          name: fd
          description: the native fd
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        200:
          description: File descriptor closed successfully.
        401:
          $ref: '#/components/responses/UnauthorizedError'
        400:
          description: Bad request. FD must be an integer greater than or equal to zero.
          content:
            text/plain:
              schema:
                type: string
        404:
          description: FD not known.
          content:
            text/plain:
              schema:
                type: string
        500:
          description: Unexpected error.
          content:
            text/plain:
              schema:
                type: string
    get:
      tags:
        - io
      summary: Read a chunk from a ProxyFD.
      operationId: read
      parameters:
        - in: path
          name: fd
          description: the native fd
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: count
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
          description: Read up to count bytes from file descriptor fd.
      responses:
        200:
          description: Content sent successfully.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        401:
          $ref: '#/components/responses/UnauthorizedError'
        400:
          description: Bad request. FD and count must be an integer greater than or equal to zero.
          content:
            text/plain:
              schema:
                type: string
        404:
          description: FD not known.
          content:
            text/plain:
              schema:
                type: string
        500:
          description: Unexpected error.
          content:
            text/plain:
              schema:
                type: string
  /fd/{fd}/stream:
    put:
      tags:
        - io
      summary: Write and stream all data to a ProxyFD until EOF.
      operationId: writeStream
      parameters:
        - in: path
          name: fd
          description: the native fd
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: chunkSize
          required: false
          schema:
            type: integer
          description: Hint to the receiving end to indicate what chunk size will be used to stream. Defaults to 64 kilobytes.
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: All content sent successfully.
        401:
          $ref: '#/components/responses/UnauthorizedError'
        400:
          description: Bad request. FD and chunkSize must be an integer greater than or equal to zero.
          content:
            text/plain:
              schema:
                type: string
        404:
          description: FD not known.
          content:
            text/plain:
              schema:
                type: string
        500:
          description: Unexpected error.
          content:
            text/plain:
              schema:
                type: string
    get:
      tags:
        - io
      summary: Read and stream all data from a ProxyFD until EOF.
      operationId: readStream
      parameters:
        - in: path
          name: fd
          description: the native fd
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: chunkSize
          required: false
          schema:
            type: integer
          description: Stream data in chunks with a maximum size. Defaults to 64 kilobytes.
      responses:
        200:
          description: All content read successfully.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        401:
          $ref: '#/components/responses/UnauthorizedError'
        400:
          description: Bad request. FD and chunkSize must be an integer greater than or equal to zero.
          content:
            text/plain:
              schema:
                type: string
        404:
          description: FD not known.
          content:
            text/plain:
              schema:
                type: string
        500:
          description: Unexpected error.
          content:
            text/plain:
              schema:
                type: string
